name: Deploy to linode ubuntu web
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Pull and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 172.104.252.159
          username: admin
          key: ${{ secrets.UBWB_PRIVATE }}
          port: 22
          script: |
            cd Git-Repos/mctest
            git pull origin master
            cp -r build/* ~/www/mctest
